apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: portal-ref-grant
  namespace: gloo-system
spec:
  from:
    - group: portal.gloo.solo.io
      kind: Portal
      namespace: default
  to:
    - group: apps
      kind: Deployment
      name: gateway-portal-web-server