apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: api-example-com
  namespace: gloo-system
  labels:
    app: quarkus-lambda-ddoyle
spec:
  virtualHost:
    domains:
    - 'lambda.example.com:81'
    routes:
    - matchers:
      - prefix: /test/
      # - prefix: /
      routeAction:
        single:
          destinationSpec:
            aws:
              logicalName: QuarkusLambdaDdoyle
              # logicalName: quarkus-lambda-app-QuarkusLambdaRestDdoyle-NTZDoZz6RBrS
              wrapAsApiGateway: false
              unwrapAsApiGateway: false
          upstream:
            name: my-aws-lambda-upstream
            namespace: gloo-system
      options:
        # prefixRewrite: "/test"
        # regexRewrite:
        #   pattern:
        #     regex: "^/test(.*)"
        #   substitution: '\1'

        # ddoyle: Implement path prefix replacement using staged transformation.
        stagedTransformations:
          regular:
            requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  extractors:
                    lambdaPathExtractor:
                      header: ':path'
                      regex: '^\/test(.*)'
                      subgroup: 1
                  headers:
                    :path:
                      text: "{{ lambdaPathExtractor }}"
        # ddoyle: This doesn't work, because we can't seem to set pseudo headers:
        # * Route Error: ProcessingError. Reason: *headers.plugin: :-prefixed headers cannot be set: ':path'. Route Name: gloo-system_api-example-com-route-0-matcher-0; Route Error: ProcessingError. Reason: *headers.plugin: :-prefixed headers cannot be set: ':path'. Route Name: gloo-system_api-example-com-route-0-matcher-0
        # headerManipulation:
        #   responseHeadersToAdd:
        #   - header:
        #       key: ":path"
        #       value: "/vertx/hello"